name: node application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: 
        echo "${{ secrets.DOCKERPW }}" | docker login -u "arnoldroshan" --password-stdin
        docker image build -t arnoldroshan/nodeapp:v1 .
        docker push arnoldroshan/nodeapp:v1
