name: Docker Image push to docker hu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "arnoldroshan" --password-stdin
        docker image build -t arnoldroshan/node:latest .
        docker push arnoldroshan/node:latest
        
