name: Docker Image push to docker hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "arnoldroshan" --password-stdin
        docker image build -t arnoldroshan/nodeapp:latest .
        docker push arnoldroshan/nodeapp:latest
        
