name: Build and Push Docker image to docker hub.

on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
  
    - name: Build and push Docker image
      run: |
         echo "${{ secrets.DOCKERPW }}"  docker login -u "arnoldroshan" --password-stdin
         docker build -t arnoldroshan/reactapp 
         docker push arnoldroshan/reactapp:v1
           
      
