name: CI

on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
  
    - name: Build and push Docker image
      run: |
        docker build -t app .
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_SECRET }}
        docker tag app arnoldroshan/test
	docker push arnoldroshan/test

