name: node appl

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: 
         docker login -u arnoldroshan -p-stdin
         docker image build -t arnoldroshan/nodeapp:v1 .
         docker push arnoldroshan/nodeapp:v1
