name: Build and Push Docker image to Docker Hub

on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v1
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "arnoldroshan" --password-stdin
        docker image build  arnoldroshan/node:latest .
        docker push arnoldroshan/node:latest
      
